default:
	echo "Please choose a target p1, p2, or p3 when running this Makefile"

p1:
	ls -l data | grep -E "\d{6}"

p2:
	grep -E ".*ii.*g$$" data/words

p3:
	ls data | grep -E "^[aeiou].*[aeiou]$$"

